env:
  browser: true
  commonjs: true
  es2021: true
  node: true
  mongo: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules: 
  indent: 2
  no-console:
    - error
    - allow: 
      - info
      - warn
      - error
  no-underscore-dangle:
    - error
    - allow:
      - _id